apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeserve-deployment
  namespace: app
  labels:
    app: kubeserve
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeserve
  template:
    metadata:
      labels:
        app: kubeserve
    spec:
      containers:
      - name: nareshdt99
        image: nareshdt99/abctechnologies-1.0
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 4
          timeoutSeconds: 120
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 4
          timeoutSeconds: 120        
        ports:
        - containerPort: 8080
