---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeserve-deployment
  labels:
    app: kubeserve
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeserve
  template:
    metadata:
      labels:
        app: kubeserve
    spec:
      containers:
      - name: kubeserve
        image: nareshdt99/abctechnologies-1.0       
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubeserve-svc
spec:
  type: NodePort
  selector:
    app: kubeserve
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
...
