apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeserve-deployment
  labels:
    app: kubeserve
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeserve
  template:
    metadata:
      labels:
        app: kubeserve
    spec:
      containers:
      - name: nareshdt99
        image: nareshdt99/abctechnologies-1.0
        ports:
        - containerPort: 8080
